name: chord_memorizer_cp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audioplayers: ^6.0.0
  rxdart: ^0.27.7
  sqflite: ^2.3.3+1
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.3+1
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon1xfresh.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/icon.png
    - assets/audio/Autumn Leaves.mp3
    - assets/audio/Misty.mp3
    - assets/audio/metronome_click.mp3
    - assets/songs/jazz.json
    - assets/songs/rock.json
    - assets/songs/country.json
    - assets/songs/pop.json
    - assets/songs/songs.json
