// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiEvkpkB8kLZDJfGwLQdyEFav6vAUAPsw',
    appId: '1:255419886147:web:4ab0bca1eb2f94d5ff82f6',
    messagingSenderId: '255419886147',
    projectId: 'chord-memorizer',
    authDomain: 'chord-memorizer.firebaseapp.com',
    storageBucket: 'chord-memorizer.firebasestorage.app',
    measurementId: 'G-J2KBG64J6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvuw5cj1fNHSXXlek1KctdAr5li7bOtnw',
    appId: '1:255419886147:android:61ade3c7a7f42f15ff82f6',
    messagingSenderId: '255419886147',
    projectId: 'chord-memorizer',
    storageBucket: 'chord-memorizer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Saz_S0gAmXHb9a9josar5wxAkajpdYY',
    appId: '1:255419886147:ios:ee91d3ce8169ee25ff82f6',
    messagingSenderId: '255419886147',
    projectId: 'chord-memorizer',
    storageBucket: 'chord-memorizer.firebasestorage.app',
    iosBundleId: 'com.example.chordMemorizerCp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Saz_S0gAmXHb9a9josar5wxAkajpdYY',
    appId: '1:255419886147:ios:ee91d3ce8169ee25ff82f6',
    messagingSenderId: '255419886147',
    projectId: 'chord-memorizer',
    storageBucket: 'chord-memorizer.firebasestorage.app',
    iosBundleId: 'com.example.chordMemorizerCp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiEvkpkB8kLZDJfGwLQdyEFav6vAUAPsw',
    appId: '1:255419886147:web:959d565a650292c8ff82f6',
    messagingSenderId: '255419886147',
    projectId: 'chord-memorizer',
    authDomain: 'chord-memorizer.firebaseapp.com',
    storageBucket: 'chord-memorizer.firebasestorage.app',
    measurementId: 'G-CZ1MT06YEF',
  );

}